apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice2
  template:
    metadata:
      labels:
        app: myservice2
    spec:
      containers:
        - image: lgdf/myservice2:1
          imagePullPolicy: IfNotPresent
          name: myservice2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myservice2
spec:
  selector:
    app: myservice2
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP